#!/usr/bin/env bash
# Display all active IPv4 IPs on the current machine

set -euo pipefail

if command -v ip >/dev/null 2>&1; then
	ip -4 addr show scope global | awk '/inet /{print $2}' | cut -d/ -f1
else
	/sbin/ifconfig 2>/dev/null | awk '/inet (addr:)?([0-9]{1,3}\.){3}[0-9]{1,3}/{print $2}' | sed 's/addr://'
fi
